export const PRODUCT_LIST_COPY = {
  title: "Produtos",
  searchPlaceholder: "Buscar produto...",
  categoryLabel: "Categoria",
  categoryAll: "Todas",
  filterAll: "Todos",
  filterOk: "Em estoque",
  filterLow: "Acabando",
  filterOut: "Zerados",
  emptyDefaultTitle: "Estoque vazio",
  emptyDefaultDescription: "Adicione o primeiro produto pela Entrada ou cadastro manual.",
  emptyFilteredTitle: "Nenhum produto encontrado",
  emptyFilteredDescription: "Tente alterar os filtros ou a busca para ver resultados.",
  listError: "Erro ao listar produtos",
};
