export const REGISTER_PAGE_COPY = {
  formTitle: "Crie sua conta",
  formSubtitle: "Use Google, Apple ou cadastre com e-mail",
  brandSubtitle: "Cadastre-se e comece a controlar o estoque da casa",
  steps: ["Dados pessoais", "Acesso", "Confirmação"],
  nameLabel: "Nome",
  stateLabel: "Estado (UF)",
  statePlaceholder: "Selecione",
  emailLabel: "E-mail",
  passwordLabel: "Senha",
  passwordHelper: "Mínimo de 8 caracteres",
  confirmPasswordLabel: "Confirmar senha",
  confirmTitle: "Confirme seus dados",
  confirmSubtitle: "Revise as informações antes de finalizar o cadastro",
  summaryName: "Nome",
  summaryState: "Estado",
  summaryEmail: "E-mail",
  emptyValue: "—",
  back: "Voltar",
  continue: "Continuar",
  submit: "Cadastrar",
  hasAccount: "Já tem uma conta?",
  loginLink: "Faça login",
  successRegister: "Cadastro realizado!",
  successNewUser: "Conta criada! Bem-vindo ao Estoque Inteligente.",
  successLogin: "Login realizado!",
  errorRegister: "Falha no cadastro",
  errorGoogle: "Falha no cadastro com Google",
  errorApple: "Falha no cadastro com Apple",
};
