export const NOTIFICATIONS_PAGE_COPY = {
  title: "Alertas",
  subtitle: "Estoque baixo, zerados e lembretes de baixa",
  loadError: "Erro ao carregar alertas",
  markReadError: "Erro ao marcar alerta como lido",
  markAllReadError: "Erro ao marcar todos como lidos",
  markAllReadSuccess: "Todos os alertas foram marcados como lidos",
  markReadSuccess: "Alerta marcado como lido",
  emptyAllTitle: "Nenhum alerta",
  emptyAllDescription: "Quando o estoque precisar de atenção, os alertas aparecem aqui.",
  emptyUnreadTitle: "Nada não lido",
  emptyUnreadDescription: "Você já viu todos os alertas por enquanto.",
  filterAll: "Todos",
  filterUnread: "Não lidos",
  markAllRead: "Marcar todos como lidos",
  markRead: "Marcar como lido",
  openProduct: "Ver produto",
  registerStockOut: "Registrar baixa",
  unreadCount: (count) =>
    count === 1 ? "1 não lido" : `${count} não lidos`,
};
