export const DASHBOARD_COPY = {
  loadError: "Erro ao carregar dashboard",
  greetingFallback: "você",
  subtitle: "Resumo do seu estoque doméstico",
  ctaIntake: "Entrada por texto",
  ctaStockOut: "Dar baixa",
  ctaShopping: "Lista de compras",
  ctaAllProducts: "Ver todos",
  attentionTitle: "Precisa de atenção",
  nothingUrgent: "Nada urgente por enquanto.",
  alertsTitle: "Alertas recentes",
  noRecentAlerts: "Nenhum alerta recente.",
  markRead: "Marcar como lido",
  openProduct: "Ver produto",
  markReadSuccess: "Alerta marcado como lido",
  markReadError: "Erro ao marcar alerta como lido",
};
