export const FINANCE_PAGE_COPY = {
  title: "Financeiro",
  subtitle: "Gastos mensais das compras em que você informou preço na entrada.",
  loadError: "Não foi possível carregar o financeiro.",
  monthTitle: "Este mês",
  projectionLabel: "Projeção do mês",
  vsPrevious: "vs. mês anterior",
  yearSeriesTitle: "Meses deste ano",
  categoriesTitle: "Por categoria",
  categoriesMonthAria: "Filtrar mês das categorias",
  tipsTitle: "Dicas (gastos + consumo)",
  tipSourceConsumption: "Consumo",
  tipSourceSpend: "Gastos",
  recentTitle: "Compras recentes",
  emptySeriesTitle: "Sem gastos no ano",
  emptySeriesDescription: "Ainda não há gastos registrados neste ano.",
  emptyCategoriesTitle: "Sem categorias",
  emptyCategoriesDescription: "Sem gastos categorizados neste mês.",
  categoriesLoadError: "Não foi possível carregar as categorias.",
  emptyTipsTitle: "Sem dicas",
  emptyTipsDescription:
    "Registre preços nas entradas e consumo (baixas) para cruzar gastos com o ritmo usual.",
  emptyRecentTitle: "Sem compras recentes",
  emptyRecentDescription: "Nenhuma compra com preço registrada.",
  storeFallback: "Compra",
  purchasesCount: (n) => (n === 1 ? "1 compra" : `${n} compras`),
};
