export const FINANCE_PAGE_COPY = {
  title: "Financeiro",
  subtitle: "Gastos das compras em que você informou preço na entrada.",
  loadError: "Não foi possível carregar o financeiro.",
  weekTitle: "Esta semana",
  monthTitle: "Este mês",
  projectionLabel: "Projeção do mês",
  vsPrevious: "vs. período anterior",
  categoriesTitle: "Por categoria",
  seriesTitle: "Últimas semanas",
  tipsTitle: "Dicas",
  recentTitle: "Compras recentes",
  emptyCategories: "Sem gastos categorizados neste mês.",
  emptySeries: "Ainda não há série de gastos.",
  emptyRecent: "Nenhuma compra com preço registrada.",
  emptyTips: "Sem dicas no momento.",
  storeFallback: "Compra",
  purchasesCount: (n) => (n === 1 ? "1 compra" : `${n} compras`),
};
