export const DASHBOARD_PAGE_COPY = {
  loadError: "Erro ao carregar dashboard",
  greetingFallback: "você",
  subtitle: "Acompanhe o estoque e registre compras com facilidade",
  ctaScanner: "Scanner de NF",
  ctaText: "Entrada por texto",
  ctaManual: "Produto manual",
  monthlySpendTitle: "Gasto deste mês",
  monthlySpendEmpty: "Sem compras com preço neste mês",
  monthlySpendCta: "Ver financeiro",
  attentionTitle: "Precisa de atenção",
  nothingUrgentTitle: "Tudo sob controle",
  nothingUrgentDescription: "Nada urgente por enquanto.",
  alertsTitle: "Alertas recentes",
  markRead: "Marcar como lido",
  openProduct: "Ver produto",
  registerStockOut: "Registrar baixa",
  markReadSuccess: "Alerta marcado como lido",
  markReadError: "Erro ao marcar alerta como lido",
};
