export const DASHBOARD_PAGE_COPY = {
  loadError: "Erro ao carregar dashboard",
  greetingFallback: "você",
  subtitle: "Acompanhe o estoque e registre compras com facilidade",
  addStockTitle: "Adicionar ao estoque",
  addStockSubtitle: "O jeito principal de alimentar o app — por nota ou por texto",
  ctaScanner: "Scanner de NF",
  ctaScannerHint: "Em breve",
  ctaText: "Entrada por texto",
  monthlySpendTitle: "Gasto deste mês",
  monthlySpendEmpty: "Sem compras com preço neste mês",
  monthlySpendCta: "Ver financeiro",
  attentionTitle: "Precisa de atenção",
  nothingUrgentTitle: "Tudo sob controle",
  nothingUrgentDescription: "Nada urgente por enquanto.",
  alertsTitle: "Alertas recentes",
  noRecentAlertsTitle: "Sem alertas recentes",
  noRecentAlertsDescription: "Quando houver novidades no estoque, elas aparecem aqui.",
  markRead: "Marcar como lido",
  openProduct: "Ver produto",
  registerStockOut: "Registrar baixa",
  markReadSuccess: "Alerta marcado como lido",
  markReadError: "Erro ao marcar alerta como lido",
  scannerComingSoon: "Scanner de NF chega na fase 2. Por enquanto use a entrada por texto.",
};
