export const DASHBOARD_PAGE_COPY = {
  loadError: "Erro ao carregar dashboard",
  greetingFallback: "você",
  subtitle: "Acompanhe o estoque e registre compras com facilidade",
  assistantTitle: "Pergunte ao assistente",
  assistantDescription:
    "Descubra o que comprar, confira o estoque e monte baixas por conversa.",
  assistantCta: "Abrir assistente",
  ctaScanner: "Scanner de NF",
  ctaAddProduct: "Adicionar novo produto",
  ctaAddProductAria: "Abrir opções para adicionar produto",
  ctaText: "Entrada por texto",
  ctaManual: "Entrada manual",
  monthlySpendTitle: "Gasto deste mês",
  monthlySpendEmpty: "Sem compras com preço neste mês",
  monthlySpendCta: "Ver financeiro",
  statOkAria: "Ver produtos em estoque",
  statLowAria: "Ver produtos acabando",
  statOutAria: "Ver produtos zerados",
  attentionTitle: "Precisa de atenção",
  nothingUrgentTitle: "Tudo sob controle",
  nothingUrgentDescription: "Nada urgente por enquanto.",
  alertsTitle: "Alertas recentes",
  markRead: "Marcar como lido",
  openProduct: "Ver produto",
  registerStockOut: "Registrar baixa",
  markReadSuccess: "Alerta marcado como lido",
  markReadError: "Erro ao marcar alerta como lido",
};
