export const INTAKE_PREVIEW_PAGE_COPY = {
  backAria: "Voltar",
  loadError: "Erro ao carregar preview",
  draftSaved: "Rascunho atualizado",
  saveDraftError: "Erro ao salvar rascunho",
  selectItemError: "Selecione ao menos um item para confirmar",
  confirmSuccessWithPurchase: (count) =>
    `Estoque atualizado (${count} itens) e compra registrada`,
  confirmSuccess: (count) => `Estoque atualizado (${count} itens)`,
  confirmError: "Erro ao confirmar entrada",
  cancelled: "Entrada cancelada",
  cancelError: "Erro ao cancelar",
  statusConfirmed: "Entrada confirmada",
  statusCancelled: "Entrada cancelada",
  statusLocked: "Este rascunho não pode mais ser editado.",
  viewProducts: "Ver produtos",
  title: "Conferir entrada",
  subtitle: "Revise os itens antes de gravar no estoque",
  rawInputLabel: "Texto original",
  storeLabel: "Estabelecimento (opcional)",
  matchedExisting: "Já no estoque",
  stockChip: (qty) => `Estoque: ${qty}`,
  excluirAria: "Excluir item",
  removeConfirmTitle: "Remover item?",
  removeConfirmDescription: (name) =>
    `Deseja remover “${name}” da revisão? Ele não entrará no estoque.`,
  removeConfirmLabel: "Remover",
  removeCancelLabel: "Cancelar",
  emptyItems: "Nenhum item na revisão. Cancele e interprete o texto novamente, ou volte.",
  nameLabel: "Nome",
  qtyLabel: "Qtd",
  unitLabel: "Unidade",
  categoryLabel: "Categoria",
  unitPriceLabel: "Preço un.",
  itemsSummary: (count) =>
    count === 1 ? "1 item será gravado" : `${count} itens serão gravados`,
  confirm: "Confirmar no estoque",
  saveDraft: "Salvar rascunho",
  cancelling: "Cancelando…",
  cancel: "Cancelar entrada",
  cancelConfirmTitle: "Cancelar entrada?",
  cancelConfirmDescription:
    "O rascunho será descartado e os itens não entrarão no estoque.",
  cancelConfirmLabel: "Cancelar entrada",
  cancelDismissLabel: "Voltar",
  expandItemAria: "Expandir ou recolher item",
};
