export const INTAKE_PREVIEW_PAGE_COPY = {
  backAria: "Voltar",
  loadError: "Erro ao carregar preview",
  draftSaved: "Rascunho atualizado",
  saveDraftError: "Erro ao salvar rascunho",
  selectItemError: "Selecione ao menos um item para confirmar",
  confirmSuccessWithPurchase: (count) =>
    `Estoque atualizado (${count} itens) e compra registrada`,
  confirmSuccess: (count) => `Estoque atualizado (${count} itens)`,
  confirmError: "Erro ao confirmar entrada",
  cancelled: "Entrada cancelada",
  cancelError: "Erro ao cancelar",
  statusConfirmed: "Entrada confirmada",
  statusCancelled: "Entrada cancelada",
  statusLocked: "Este rascunho não pode mais ser editado.",
  viewProducts: "Ver produtos",
  title: "Conferir compra",
  subtitle: "Revise os itens antes de gravar no estoque",
  rawInputLabel: "Texto original",
  storeLabel: "Estabelecimento (opcional)",
  matchedExisting: "Já no estoque",
  reincluirAria: "Reincluir item",
  excluirAria: "Excluir item",
  nameLabel: "Nome",
  qtyLabel: "Qtd",
  unitLabel: "Unidade",
  categoryLabel: "Categoria",
  unitPriceLabel: "Preço un.",
  itemsSummary: (active, total) => `${active} de ${total} item(ns) serão gravados`,
  confirm: "Confirmar no estoque",
  saveDraft: "Salvar rascunho",
  cancelling: "Cancelando…",
  cancel: "Cancelar entrada",
  confidenceHigh: "Alta confiança",
  confidenceMedium: "Média confiança",
  confidenceLow: "Baixa confiança",
};
