export const LOGIN_PAGE_COPY = {
  formTitle: "Acesse sua conta",
  brandSubtitle: "Gerencie seu estoque doméstico com praticidade",
  emailLabel: "E-mail",
  passwordLabel: "Senha",
  submit: "Entrar",
  forgotPassword: "Esqueci minha senha",
  noAccount: "Não tem conta?",
  signUpLink: "Cadastre-se",
  successLogin: "Login realizado!",
  successNewUser: "Conta criada! Bem-vindo ao Estoque Inteligente.",
  errorLogin: "Falha no login",
  errorGoogle: "Não foi possível entrar com Google. Tente novamente.",
  errorApple: "Não foi possível entrar com Apple. Tente novamente.",
};
