export const STOCK_OUT_PREVIEW_PAGE_COPY = {
  backAria: "Voltar",
  loadError: "Erro ao carregar preview",
  selectItemError: "Selecione ao menos um item para confirmar",
  linkProductError: "Vincule um produto para todos os itens ativos",
  confirmSuccess: (count) => `Baixa confirmada (${count} itens)`,
  confirmError: "Erro ao confirmar baixa",
  cancelled: "Baixa cancelada",
  cancelError: "Erro ao cancelar",
  statusConfirmed: "Baixa confirmada",
  statusCancelled: "Baixa cancelada",
  viewProducts: "Ver produtos",
  title: "Conferir baixa",
  subtitle: "Revise antes de descontar do estoque",
  rawInputLabel: "Texto original",
  stockChip: (qty) => `Estoque: ${qty}`,
  productLabel: "Nome",
  selectProduct: "Selecione",
  qtyLabel: "Qtd",
  unitLabel: "Unidade",
  allowZeroLabel: "Zerar o produto se a quantidade passar do estoque",
  itemsSummary: (count) =>
    count === 1 ? "1 item será baixado" : `${count} itens serão baixados`,
  emptyItems: "Nenhum item na revisão. Cancele e interprete o texto novamente, ou volte.",
  excluirAria: "Excluir item",
  expandItemAria: "Expandir ou recolher item",
  removeConfirmTitle: "Remover item?",
  removeConfirmDescription: (name) =>
    `Deseja remover “${name}” da revisão? Ele não será baixado do estoque.`,
  removeConfirmLabel: "Remover",
  removeCancelLabel: "Cancelar",
  confirm: "Confirmar baixa",
  cancel: "Cancelar baixa",
  cancelConfirmTitle: "Cancelar baixa?",
  cancelConfirmDescription:
    "O rascunho será descartado e nenhum item será descontado do estoque.",
  cancelConfirmLabel: "Cancelar baixa",
  cancelDismissLabel: "Voltar",
};
