export const STOCK_OUT_PREVIEW_PAGE_COPY = {
  backAria: "Voltar",
  loadError: "Erro ao carregar preview",
  selectItemError: "Selecione ao menos um item para confirmar",
  linkProductError: "Vincule um produto para todos os itens ativos",
  confirmSuccess: (count) => `Baixa confirmada (${count} itens)`,
  confirmError: "Erro ao confirmar baixa",
  cancelled: "Baixa cancelada",
  cancelError: "Erro ao cancelar",
  statusConfirmed: "Baixa confirmada",
  statusCancelled: "Baixa cancelada",
  viewProducts: "Ver produtos",
  title: "Conferir baixa",
  subtitle: "Revise antes de descontar do estoque",
  stockChip: (qty) => `Estoque: ${qty}`,
  productLabel: "Produto no estoque",
  selectProduct: "Selecione",
  qtyLabel: "Qtd",
  unitLabel: "Unidade",
  allowZeroLabel: "Zerar o produto se a quantidade passar do estoque",
  itemsSummary: (active, total) => `${active} de ${total} item(ns) serão baixados`,
  confirm: "Confirmar baixa",
  cancelling: "Cancelando…",
  cancel: "Cancelar baixa",
  warningProductNotFound: "Produto não encontrado",
  warningExceedsStock: "Quantidade maior que o estoque",
};
