export const PRODUCT_CREATE_COPY = {
  title: "Cadastro manual",
  subtitle: "Monte a lista e salve tudo de uma vez",
  nameLabel: "Nome",
  categoryLabel: "Categoria",
  quantityLabel: "Quantidade",
  unitLabel: "Unidade",
  minQuantityLabel: "Quantidade mínima",
  notesLabel: "Observações",
  addToStage: "Adicionar à lista",
  updateStage: "Atualizar item",
  cancelEdit: "Cancelar edição",
  stageTitle: "Na lista",
  stageEmpty: "Nenhum produto na lista ainda. Preencha o formulário e toque em “Adicionar à lista”.",
  removeItem: "Remover",
  editItem: "Editar",
  saveAll: (n) => (n === 1 ? "Salvar 1 produto" : `Salvar ${n} produtos`),
  successAll: (n) => (n === 1 ? "1 produto criado" : `${n} produtos criados`),
  partialSuccess: (ok, fail) =>
    `${ok} criado(s). ${fail} não puderam ser salvos — confira os nomes duplicados.`,
  error: "Erro ao criar produtos",
  duplicateInStage: "Este nome já está na lista",
  loadMetaError: "Não foi possível carregar categorias e unidades",
};
