export const HEADER_COPY = {
  logoAlt: "Estoque Inteligente",
  avatarTooltip: "Perfil e opções",
  loadingUser: "Carregando...",
  alertas: "Alertas",
  minhaConta: "Minha conta",
  sair: "Sair",
  logoutTitle: "Confirmar saída",
  logoutDescription: "Tem certeza que deseja sair da sua conta?",
  logoutCancel: "Cancelar",
  logoutConfirm: "Sair",
  closeMenuAria: "Fechar menu",
  openMenuAria: "Abrir menu",
  avatarFallback: "U",
};
