export const MY_ACCOUNT_COPY = {
  title: "Minha conta",
  profileTitle: "Perfil",
  nameLabel: "Nome",
  defaultStateLabel: "UF padrão",
  saveProfile: "Salvar perfil",
  profileSuccess: "Perfil atualizado",
  profileError: "Erro ao atualizar perfil",
  linkSocialTitle: "Vincular login social",
  linkSocialDescription: "Conecte Google ou Apple para entrar sem senha na próxima vez.",
  linkAppleLabel: "Vincular Apple",
  googleLinked: "Google vinculado",
  googleAlreadyLinked: "Google já estava vinculado",
  googleLinkError: "Falha ao vincular Google",
  appleLinked: "Apple vinculada",
  appleAlreadyLinked: "Apple já estava vinculada",
  appleLinkError: "Falha ao vincular Apple",
  passwordTitle: "Senha",
  currentPasswordLabel: "Senha atual",
  newPasswordLabel: "Nova senha",
  confirmPasswordLabel: "Confirmar nova senha",
  updatePassword: "Atualizar senha",
  passwordSuccess: "Senha atualizada",
  passwordError: "Erro ao trocar senha",
  alertsTitle: "Alertas e lembretes",
  alertsSubtitle: "Escolha o que deseja receber no app",
  notifyLowStock: "Estoque baixo",
  notifyOutOfStock: "Estoque zerado",
  notifyConsumptionNudge: "Lembrete periódico de baixa",
  consumptionNudgeDays: "Intervalo do lembrete (dias)",
  consumptionNudgeDaysHelper: "Entre 1 e 30 dias sem baixas",
  savePreferences: "Salvar preferências",
  preferencesSuccess: "Preferências atualizadas",
  preferencesError: "Erro ao salvar preferências",
  preferencesLoadError: "Erro ao carregar preferências",
  logout: "Sair da conta",
};
