export const MY_ACCOUNT_RESUMO_COPY = {
  editarDados: "Editar dados",
  alterarSenha: "Alterar Senha",
  logout: "Sair da conta",
  phoneLabel: "Telefone",
  cpfLabel: "CPF",
  estadoLabel: "Estado",
  zipCodeLabel: "CEP",
  addressLabel: "Endereço",
  emptyEstado: "Não definido",
  emptyValue: "Não informado",
};

export const EDIT_PROFILE_DIALOG_COPY = {
  title: "Editar dados",
  firstNameLabel: "Nome *",
  lastNameLabel: "Sobrenome *",
  emailLabel: "E-mail",
  phoneLabel: "Telefone",
  cpfLabel: "CPF",
  zipCodeLabel: "CEP",
  zipCodeLookupError: "Não foi possível localizar o CEP",
  streetLabel: "Rua",
  streetNumberLabel: "Número",
  complementLabel: "Complemento",
  neighborhoodLabel: "Bairro",
  cityLabel: "Cidade",
  estadoLabel: "Estado",
  cancelar: "Cancelar",
  salvar: "Salvar",
};

export const CHANGE_PASSWORD_DIALOG_COPY = {
  title: "Alterar Senha",
  currentPassword: "Senha Atual",
  newPassword: "Nova Senha *",
  confirmPassword: "Confirmar Nova Senha *",
  cancelar: "Cancelar",
  salvar: "Salvar Senha",
};

export const MY_ACCOUNT_PAGE_COPY = {
  title: "Minha Conta",
  subtitle: "Gerencie seus dados, alertas e formas de acesso",
  profileSuccess: "Dados atualizados com sucesso!",
  profileError: "Não foi possível atualizar os dados da conta.",
  passwordSuccess: "Senha alterada com sucesso!",
  passwordError: "Não foi possível alterar a senha.",
  linkSocialTitle: "Vincular login social",
  linkSocialDescription: "Conecte Google ou Apple para entrar sem senha na próxima vez.",
  linkAppleLabel: "Vincular Apple",
  googleLinked: "Google vinculado",
  googleAlreadyLinked: "Google já estava vinculado",
  googleLinkError: "Falha ao vincular Google",
  appleLinked: "Apple vinculada",
  appleAlreadyLinked: "Apple já estava vinculada",
  appleLinkError: "Falha ao vincular Apple",
  alertsTitle: "Alertas e lembretes",
  alertsSubtitle: "Escolha o que deseja receber no app",
  notifyLowStock: "Estoque baixo",
  notifyOutOfStock: "Estoque zerado",
  notifyConsumptionNudge: "Lembrete periódico de baixa",
  consumptionNudgeDays: "Intervalo do lembrete (dias)",
  savePreferences: "Salvar preferências",
  preferencesSuccess: "Preferências atualizadas",
  preferencesError: "Erro ao salvar preferências",
  preferencesLoadError: "Erro ao carregar preferências",
};
