export const PRODUCT_DETAIL_COPY = {
  loadError: "Erro ao carregar produto",
  consumeSuccess: "Baixa registrada",
  consumeError: "Erro ao dar baixa",
  markOutSuccess: "Produto marcado como acabou",
  markOutError: "Erro ao zerar produto",
  updateSuccess: "Produto atualizado",
  updateError: "Erro ao atualizar produto",
  editAction: "Editar",
  consumeAction: "Dar baixa",
  markOutAction: "Marcar acabou",
  deleteAction: "Excluir",
  deleteConfirmTitle: "Excluir produto?",
  deleteConfirmDescription: (name) =>
    `"${name}" sai do estoque e da lista de compras. O histórico de movimentos e compras é mantido.`,
  deleteConfirmLabel: "Excluir",
  deleteCancelLabel: "Cancelar",
  deleteSuccess: "Produto excluído",
  deleteError: "Não foi possível excluir o produto.",
  historyTitle: "Histórico",
  historyEmpty: "Sem movimentos ainda.",
  minPrefix: "mínimo",
  unitPriceLabel: (priceLabel) => `Preço unitário: ${priceLabel}`,
  unitPriceEmpty: "Sem preço unitário cadastrado",
  repurchaseLabel: (days) => `Recompra a cada ${days} dias`,
  repurchaseEmpty: "Sem intervalo de recompra definido",
  movementIn: "+",
  movementOut: "−",
  movementAdjust: "±",
};
