export const PRODUCT_DETAIL_COPY = {
  loadError: "Erro ao carregar produto",
  consumeSuccess: "Baixa registrada",
  consumeError: "Erro ao dar baixa",
  markOutSuccess: "Produto marcado como acabou",
  markOutError: "Erro ao zerar produto",
  updateSuccess: "Produto atualizado",
  updateError: "Erro ao atualizar produto",
  editAction: "Editar",
  consumeAction: "Dar baixa",
  markOutAction: "Marcar acabou",
  historyTitle: "Histórico",
  historyEmpty: "Sem movimentos ainda.",
  minPrefix: "mínimo",
  unitPriceLabel: (priceLabel) => `Preço unitário: ${priceLabel}`,
  unitPriceEmpty: "Sem preço unitário cadastrado",
  repurchaseLabel: (days) => `Recompra a cada ${days} dias`,
  repurchaseEmpty: "Sem intervalo de recompra definido",
  movementIn: "+",
  movementOut: "−",
  movementAdjust: "±",
};
