export const SHOPPING_LIST_PAGE_COPY = {
  loadError: "Erro ao carregar lista",
  generatePending: (pending) => `Lista atualizada (${pending} pendentes)`,
  generateEmpty: "Nada novo para sugerir agora",
  generateError: "Erro ao gerar lista",
  viewModeError: "Erro ao salvar visualização",
  toggleError: "Erro ao atualizar item",
  itemRemoved: "Item removido",
  deleteError: "Erro ao remover item",
  deleteConfirmTitle: "Remover item?",
  deleteConfirmDescription: (name) =>
    `Deseja remover “${name}” da lista de compras? Essa ação não pode ser desfeita.`,
  deleteConfirmLabel: "Remover",
  deleteCancelLabel: "Cancelar",
  itemsAdded: (count) => `${count} itens adicionados à lista`,
  itemAdded: "Item adicionado",
  itemsMerged: "Itens iguais foram somados na lista",
  itemsAddedAndMerged: (added, merged) =>
    `${added} novo(s) · ${merged} somado(s) na lista`,
  addError: "Erro ao adicionar item",
  title: "Lista de compras",
  subtitle: "Monte a lista pelo estoque ou por texto",
  generate: "Gerar lista automática",
  viewList: "Lista",
  viewPaper: "Paper",
  viewModeAria: "Modo de visualização",
  stats: (pending, checked) => `${pending} pendente(s) · ${checked} marcado(s)`,
  addSectionTitle: "Adicionar por texto",
  addLabel: "O que você precisa comprar?",
  addPlaceholder: "Ex.: 2kg de arroz, 1 lata de leite em pó",
  addSubmit: "Adicionar",
};
